# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "20"

sphinx:
  configuration: src/conf.py

python:
  install:
    - requirements: cfg/requirements.txt
