#!/usr/bin/bash

cd img/py
rm -rf venv
python -m venv venv
source venv/bin/activate
pip install --cache-dir /app/img/cache -r requirements.txt
pip list -o > venv/up.txt

eval "$(python /app/img/pack.py)"

echo "PIP Changes: $PIP_CHANGES"
if [ "$PIP_CHANGES" == "True" ]; then
    deactivate
    rm -rf venv
    python -m venv venv
    source venv/bin/activate
    pip install --cache-dir /app/img/cache -r requirements.txt
fi
