#!/usr/bin/bash

cd img/md
source venv/bin/activate
pip list -o > venv/up.txt

eval "$(python pack.py)"

echo "PIP Changes: $PIP_CHANGES"
if [ "$PIP_CHANGES" == "True" ]; then
    deactivate
    cp -f requirements.txt /app/cfg/
    rm -rf venv
    python -m venv venv
    source venv/bin/activate
    pip install --no-cache-dir -r requirements.txt
fi

rm venv/up.txt
cd /app
export PATH=$PATH:/app/img/md/venv/bin

sphinx-build -M html /app/src /app/doc

deactivate
